language: objective-c
osx_image: xcode9

cache:
  - bundler
  - cocoapods

env:
  global:
    - WORKSPACE="ABTest.xcworkspace"
    - SCHEME="ABTest"
    - IOS_SDK="iphonesimulator11.0"
  matrix:
    - SDK="$IOS_SDK"  DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=11.0"

install:
  - bundle install --deployment
  - bundle exec pod --version
  - bundle exec pod repo update --verbose
  - bundle exec pod install

script:
  - xcodebuild clean build test
    -workspace "$WORKSPACE"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
