language: objective-c
osx_image: xcode9

cache:
  - bundler
  - cocoapods

env:
  global:
    - WORKSPACE="ABTest.xcworkspace"
    - IOS_SDK="iphonesimulator11.0"
    - IOS_DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=11.0"
  matrix:
    - SCHEME="ABTest"        SDK="$IOS_SDK"      ACTION="test"

script:
  - set -o pipefail && xcodebuild clean $ACTION -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$IOS_DESTINATION" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
